// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/auction_engine.proto

package auctionpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuctionEngine_PlaceBid_FullMethodName = "/auctionengine.AuctionEngine/PlaceBid"
)

// AuctionEngineClient is the client API for AuctionEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionEngineClient interface {
	PlaceBid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidAccepted, error)
}

type auctionEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionEngineClient(cc grpc.ClientConnInterface) AuctionEngineClient {
	return &auctionEngineClient{cc}
}

func (c *auctionEngineClient) PlaceBid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidAccepted, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidAccepted)
	err := c.cc.Invoke(ctx, AuctionEngine_PlaceBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionEngineServer is the server API for AuctionEngine service.
// All implementations must embed UnimplementedAuctionEngineServer
// for forward compatibility.
type AuctionEngineServer interface {
	PlaceBid(context.Context, *BidRequest) (*BidAccepted, error)
	mustEmbedUnimplementedAuctionEngineServer()
}

// UnimplementedAuctionEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuctionEngineServer struct{}

func (UnimplementedAuctionEngineServer) PlaceBid(context.Context, *BidRequest) (*BidAccepted, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBid not implemented")
}
func (UnimplementedAuctionEngineServer) mustEmbedUnimplementedAuctionEngineServer() {}
func (UnimplementedAuctionEngineServer) testEmbeddedByValue()                       {}

// UnsafeAuctionEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionEngineServer will
// result in compilation errors.
type UnsafeAuctionEngineServer interface {
	mustEmbedUnimplementedAuctionEngineServer()
}

func RegisterAuctionEngineServer(s grpc.ServiceRegistrar, srv AuctionEngineServer) {
	// If the following call panics, it indicates UnimplementedAuctionEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuctionEngine_ServiceDesc, srv)
}

func _AuctionEngine_PlaceBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionEngineServer).PlaceBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionEngine_PlaceBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionEngineServer).PlaceBid(ctx, req.(*BidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuctionEngine_ServiceDesc is the grpc.ServiceDesc for AuctionEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auctionengine.AuctionEngine",
	HandlerType: (*AuctionEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceBid",
			Handler:    _AuctionEngine_PlaceBid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auction_engine.proto",
}
