// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/auction_engine.proto

package auctionpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidRejectionCode int32

const (
	BidRejectionCode_UNSPECIFIED               BidRejectionCode = 0
	BidRejectionCode_AUCTION_UNAVAILABLE       BidRejectionCode = 1
	BidRejectionCode_AUCTION_ENDED             BidRejectionCode = 2
	BidRejectionCode_BID_TOO_LOW               BidRejectionCode = 3
	BidRejectionCode_BIDDER_ALREADY_PLACED_BID BidRejectionCode = 4
)

// Enum value maps for BidRejectionCode.
var (
	BidRejectionCode_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "AUCTION_UNAVAILABLE",
		2: "AUCTION_ENDED",
		3: "BID_TOO_LOW",
		4: "BIDDER_ALREADY_PLACED_BID",
	}
	BidRejectionCode_value = map[string]int32{
		"UNSPECIFIED":               0,
		"AUCTION_UNAVAILABLE":       1,
		"AUCTION_ENDED":             2,
		"BID_TOO_LOW":               3,
		"BIDDER_ALREADY_PLACED_BID": 4,
	}
)

func (x BidRejectionCode) Enum() *BidRejectionCode {
	p := new(BidRejectionCode)
	*p = x
	return p
}

func (x BidRejectionCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidRejectionCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auction_engine_proto_enumTypes[0].Descriptor()
}

func (BidRejectionCode) Type() protoreflect.EnumType {
	return &file_proto_auction_engine_proto_enumTypes[0]
}

func (x BidRejectionCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidRejectionCode.Descriptor instead.
func (BidRejectionCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_auction_engine_proto_rawDescGZIP(), []int{0}
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionID     string                 `protobuf:"bytes,1,opt,name=auctionID,proto3" json:"auctionID,omitempty"`
	BidderId      string                 `protobuf:"bytes,2,opt,name=bidderId,proto3" json:"bidderId,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_proto_auction_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_engine_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetAuctionID() string {
	if x != nil {
		return x.AuctionID
	}
	return ""
}

func (x *BidRequest) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *BidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BidAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionID     string                 `protobuf:"bytes,1,opt,name=auctionID,proto3" json:"auctionID,omitempty"`
	BidderId      string                 `protobuf:"bytes,2,opt,name=bidderId,proto3" json:"bidderId,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidAccepted) Reset() {
	*x = BidAccepted{}
	mi := &file_proto_auction_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAccepted) ProtoMessage() {}

func (x *BidAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAccepted.ProtoReflect.Descriptor instead.
func (*BidAccepted) Descriptor() ([]byte, []int) {
	return file_proto_auction_engine_proto_rawDescGZIP(), []int{1}
}

func (x *BidAccepted) GetAuctionID() string {
	if x != nil {
		return x.AuctionID
	}
	return ""
}

func (x *BidAccepted) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *BidAccepted) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// BidRejected is returned as a google.rpc.Status detail when PlaceBid fails
// because the auction domain rejected the bid.
type BidRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          BidRejectionCode       `protobuf:"varint,1,opt,name=code,proto3,enum=auctionengine.BidRejectionCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRejected) Reset() {
	*x = BidRejected{}
	mi := &file_proto_auction_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRejected) ProtoMessage() {}

func (x *BidRejected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRejected.ProtoReflect.Descriptor instead.
func (*BidRejected) Descriptor() ([]byte, []int) {
	return file_proto_auction_engine_proto_rawDescGZIP(), []int{2}
}

func (x *BidRejected) GetCode() BidRejectionCode {
	if x != nil {
		return x.Code
	}
	return BidRejectionCode_UNSPECIFIED
}

func (x *BidRejected) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_auction_engine_proto protoreflect.FileDescriptor

const file_proto_auction_engine_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/auction_engine.proto\x12\rauctionengine\"^\n" +
	"\n" +
	"BidRequest\x12\x1c\n" +
	"\tauctionID\x18\x01 \x01(\tR\tauctionID\x12\x1a\n" +
	"\bbidderId\x18\x02 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"_\n" +
	"\vBidAccepted\x12\x1c\n" +
	"\tauctionID\x18\x01 \x01(\tR\tauctionID\x12\x1a\n" +
	"\bbidderId\x18\x02 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\\\n" +
	"\vBidRejected\x123\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1f.auctionengine.BidRejectionCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x7f\n" +
	"\x10BidRejectionCode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AUCTION_UNAVAILABLE\x10\x01\x12\x11\n" +
	"\rAUCTION_ENDED\x10\x02\x12\x0f\n" +
	"\vBID_TOO_LOW\x10\x03\x12\x1d\n" +
	"\x19BIDDER_ALREADY_PLACED_BID\x10\x042T\n" +
	"\rAuctionEngine\x12C\n" +
	"\bPlaceBid\x12\x19.auctionengine.BidRequest\x1a\x1a.auctionengine.BidAccepted\"\x00BRZPgithub.com/Metololo/realtime_bidding_system/proto/auction_engine_proto;auctionpbb\x06proto3"

var (
	file_proto_auction_engine_proto_rawDescOnce sync.Once
	file_proto_auction_engine_proto_rawDescData []byte
)

func file_proto_auction_engine_proto_rawDescGZIP() []byte {
	file_proto_auction_engine_proto_rawDescOnce.Do(func() {
		file_proto_auction_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auction_engine_proto_rawDesc), len(file_proto_auction_engine_proto_rawDesc)))
	})
	return file_proto_auction_engine_proto_rawDescData
}

var file_proto_auction_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_auction_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_auction_engine_proto_goTypes = []any{
	(BidRejectionCode)(0), // 0: auctionengine.BidRejectionCode
	(*BidRequest)(nil),    // 1: auctionengine.BidRequest
	(*BidAccepted)(nil),   // 2: auctionengine.BidAccepted
	(*BidRejected)(nil),   // 3: auctionengine.BidRejected
}
var file_proto_auction_engine_proto_depIdxs = []int32{
	0, // 0: auctionengine.BidRejected.code:type_name -> auctionengine.BidRejectionCode
	1, // 1: auctionengine.AuctionEngine.PlaceBid:input_type -> auctionengine.BidRequest
	2, // 2: auctionengine.AuctionEngine.PlaceBid:output_type -> auctionengine.BidAccepted
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_auction_engine_proto_init() }
func file_proto_auction_engine_proto_init() {
	if File_proto_auction_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auction_engine_proto_rawDesc), len(file_proto_auction_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auction_engine_proto_goTypes,
		DependencyIndexes: file_proto_auction_engine_proto_depIdxs,
		EnumInfos:         file_proto_auction_engine_proto_enumTypes,
		MessageInfos:      file_proto_auction_engine_proto_msgTypes,
	}.Build()
	File_proto_auction_engine_proto = out.File
	file_proto_auction_engine_proto_goTypes = nil
	file_proto_auction_engine_proto_depIdxs = nil
}
