// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/events.proto

package auctionpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuctionOutcome int32

const (
	AuctionOutcome_AUCTION_OUTCOME_UNSPECIFIED AuctionOutcome = 0
	AuctionOutcome_AUCTION_OUTCOME_SOLD        AuctionOutcome = 1
	AuctionOutcome_AUCTION_OUTCOME_NO_BIDS     AuctionOutcome = 2
)

// Enum value maps for AuctionOutcome.
var (
	AuctionOutcome_name = map[int32]string{
		0: "AUCTION_OUTCOME_UNSPECIFIED",
		1: "AUCTION_OUTCOME_SOLD",
		2: "AUCTION_OUTCOME_NO_BIDS",
	}
	AuctionOutcome_value = map[string]int32{
		"AUCTION_OUTCOME_UNSPECIFIED": 0,
		"AUCTION_OUTCOME_SOLD":        1,
		"AUCTION_OUTCOME_NO_BIDS":     2,
	}
)

func (x AuctionOutcome) Enum() *AuctionOutcome {
	p := new(AuctionOutcome)
	*p = x
	return p
}

func (x AuctionOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_events_proto_enumTypes[0].Descriptor()
}

func (AuctionOutcome) Type() protoreflect.EnumType {
	return &file_proto_events_proto_enumTypes[0]
}

func (x AuctionOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionOutcome.Descriptor instead.
func (AuctionOutcome) EnumDescriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

type AuctionCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	AuctionId     string                 `protobuf:"bytes,3,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ReservePrice  int64                  `protobuf:"varint,5,opt,name=reserve_price,json=reservePrice,proto3" json:"reserve_price,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionCreatedEvent) Reset() {
	*x = AuctionCreatedEvent{}
	mi := &file_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionCreatedEvent) ProtoMessage() {}

func (x *AuctionCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionCreatedEvent.ProtoReflect.Descriptor instead.
func (*AuctionCreatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *AuctionCreatedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuctionCreatedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AuctionCreatedEvent) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *AuctionCreatedEvent) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AuctionCreatedEvent) GetReservePrice() int64 {
	if x != nil {
		return x.ReservePrice
	}
	return 0
}

func (x *AuctionCreatedEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AuctionCreatedEvent) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type WinnerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidderId      string                 `protobuf:"bytes,1,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinnerInfo) Reset() {
	*x = WinnerInfo{}
	mi := &file_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinnerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinnerInfo) ProtoMessage() {}

func (x *WinnerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinnerInfo.ProtoReflect.Descriptor instead.
func (*WinnerInfo) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *WinnerInfo) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *WinnerInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AuctionClosedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	AuctionId     string                 `protobuf:"bytes,3,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Outcome       AuctionOutcome         `protobuf:"varint,5,opt,name=outcome,proto3,enum=auctionevents.AuctionOutcome" json:"outcome,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	Winner        *WinnerInfo            `protobuf:"bytes,7,opt,name=winner,proto3" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionClosedEvent) Reset() {
	*x = AuctionClosedEvent{}
	mi := &file_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionClosedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionClosedEvent) ProtoMessage() {}

func (x *AuctionClosedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionClosedEvent.ProtoReflect.Descriptor instead.
func (*AuctionClosedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionClosedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuctionClosedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AuctionClosedEvent) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *AuctionClosedEvent) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AuctionClosedEvent) GetOutcome() AuctionOutcome {
	if x != nil {
		return x.Outcome
	}
	return AuctionOutcome_AUCTION_OUTCOME_UNSPECIFIED
}

func (x *AuctionClosedEvent) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *AuctionClosedEvent) GetWinner() *WinnerInfo {
	if x != nil {
		return x.Winner
	}
	return nil
}

var File_proto_events_proto protoreflect.FileDescriptor

const file_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x12proto/events.proto\x12\rauctionevents\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x02\n" +
	"\x13AuctionCreatedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x03 \x01(\tR\tauctionId\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\tR\x06itemId\x12#\n" +
	"\rreserve_price\x18\x05 \x01(\x03R\freservePrice\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x121\n" +
	"\x06end_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"A\n" +
	"\n" +
	"WinnerInfo\x12\x1b\n" +
	"\tbidder_id\x18\x01 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\xc9\x02\n" +
	"\x12AuctionClosedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x03 \x01(\tR\tauctionId\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\tR\x06itemId\x127\n" +
	"\aoutcome\x18\x05 \x01(\x0e2\x1d.auctionevents.AuctionOutcomeR\aoutcome\x127\n" +
	"\tclosed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x121\n" +
	"\x06winner\x18\a \x01(\v2\x19.auctionevents.WinnerInfoR\x06winner*h\n" +
	"\x0eAuctionOutcome\x12\x1f\n" +
	"\x1bAUCTION_OUTCOME_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AUCTION_OUTCOME_SOLD\x10\x01\x12\x1b\n" +
	"\x17AUCTION_OUTCOME_NO_BIDS\x10\x02BIZGgithub.com/Metololo/realtime_bidding_system/proto/events_proto;eventspbb\x06proto3"

var (
	file_proto_events_proto_rawDescOnce sync.Once
	file_proto_events_proto_rawDescData []byte
)

func file_proto_events_proto_rawDescGZIP() []byte {
	file_proto_events_proto_rawDescOnce.Do(func() {
		file_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)))
	})
	return file_proto_events_proto_rawDescData
}

var file_proto_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_events_proto_goTypes = []any{
	(AuctionOutcome)(0),           // 0: auctionevents.AuctionOutcome
	(*AuctionCreatedEvent)(nil),   // 1: auctionevents.AuctionCreatedEvent
	(*WinnerInfo)(nil),            // 2: auctionevents.WinnerInfo
	(*AuctionClosedEvent)(nil),    // 3: auctionevents.AuctionClosedEvent
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_events_proto_depIdxs = []int32{
	4, // 0: auctionevents.AuctionCreatedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	4, // 1: auctionevents.AuctionCreatedEvent.started_at:type_name -> google.protobuf.Timestamp
	4, // 2: auctionevents.AuctionCreatedEvent.end_at:type_name -> google.protobuf.Timestamp
	4, // 3: auctionevents.AuctionClosedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 4: auctionevents.AuctionClosedEvent.outcome:type_name -> auctionevents.AuctionOutcome
	4, // 5: auctionevents.AuctionClosedEvent.closed_at:type_name -> google.protobuf.Timestamp
	2, // 6: auctionevents.AuctionClosedEvent.winner:type_name -> auctionevents.WinnerInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_events_proto_init() }
func file_proto_events_proto_init() {
	if File_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_proto_goTypes,
		DependencyIndexes: file_proto_events_proto_depIdxs,
		EnumInfos:         file_proto_events_proto_enumTypes,
		MessageInfos:      file_proto_events_proto_msgTypes,
	}.Build()
	File_proto_events_proto = out.File
	file_proto_events_proto_goTypes = nil
	file_proto_events_proto_depIdxs = nil
}
